-- POPOLAMENTO TABELLA DIPENDENTI
INSERT INTO TESTAUTOMATICI.DIPENDENTI (MATRICOLA, NOME, COGNOME) VALUES ('AAA', 'Pino', 'Philip');
INSERT INTO TESTAUTOMATICI.DIPENDENTI (MATRICOLA, NOME, COGNOME) VALUES ('AAA', 'Rosa', 'Foglio');
INSERT INTO TESTAUTOMATICI.DIPENDENTI (MATRICOLA, NOME, COGNOME) VALUES ('AAA', 'Guido', 'Male');
