-- POPOLAMENTO TABELLA DIPENDENTI
INSERT INTO TESTAUTOMATICI.DIPENDENTI (MATRICOLA, NOME, COGNOME) VALUES ('ZZZ', 'Pino', 'Philip');
INSERT INTO TESTAUTOMATICI.DIPENDENTI (MATRICOLA, NOME, COGNOME) VALUES ('WWW', 'Rosa', 'Foglio');
INSERT INTO TESTAUTOMATICI.DIPENDENTI (MATRICOLA, NOME, COGNOME) VALUES ('YYY', 'Guido', 'Male');
