CREATE SCHEMA IF NOT EXISTS TESTAUTOMATICI;

CREATE TABLE IF NOT EXISTS TESTAUTOMATICI.DIPENDENTI
(
   MATRICOLA CHAR(10) NOT NULL,
   NOME      CHAR(50) NOT NULL,
   COGNOME   CHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS TESTAUTOMATICI.STIPENDI
(
    MATRICOLA   CHAR(10) NOT NULL,
    IMPORTO     DECIMAL(14,3) NOT NULL,
    DATA_INIZIO DATE NOT NULL,
    DATA_FINE   DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS TESTAUTOMATICI.ASSENZE
(
    MATRICOLA    CHAR(10) NOT NULL,
    DATA_ASSENZA DATE NOT NULL
);
